### ISSUE TITLE
fehlermeldung

### ISSUE THREAD

**Issue by MaJaWe1975** [iobroker-community-adapters/ioBroker.onvif#111]
Kann mir jemand bei dem fehler weiterhelfen? kommt alle 60 sekunden 

![image](https://github.com/iobroker-community-adapters/ioBroker.onvif/assets/64575410/cdda0321-ef18-4b84-88a4-dff4b989b896)

**Comment by TA2k** [comment]
Ist es eine Tapo?
Ein debug log via email wäre interessant
tombox2020@gmail.com

**Comment by MaJaWe1975** [comment]
Mail ist raus ;-)

Es sind 2 Hikvision cams

![image](https://github.com/iobroker-community-adapters/ioBroker.onvif/assets/64575410/004b3111-9ad5-4ee4-b0ec-504047d1a8cc)

**Comment by TA2k** [comment]
bitt meal die GitHub version testen wie die sich verhält

**Comment by MaJaWe1975** [comment]
jetzt geht es, danke
